(function() {var implementors = {};
implementors["handlebars"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='handlebars/struct.Template.html' title='handlebars::Template'>Template</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='handlebars/enum.TemplateError.html' title='handlebars::TemplateError'>TemplateError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='handlebars/enum.TemplateFileError.html' title='handlebars::TemplateFileError'>TemplateFileError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='handlebars/enum.TemplateRenderError.html' title='handlebars::TemplateRenderError'>TemplateRenderError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='handlebars/struct.RenderError.html' title='handlebars::RenderError'>RenderError</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='handlebars/struct.RenderContext.html' title='handlebars::RenderContext'>RenderContext</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='handlebars/struct.ContextJson.html' title='handlebars::ContextJson'>ContextJson</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='handlebars/struct.Context.html' title='handlebars::Context'>Context</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
